version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: tiersense_backend
    volumes:
      - ./backend:/app
      - /var/log/sharedlogs:/var/log/sharedlogs  # NFS mount point inside container
    ports:
      - "8000:8000"
    working_dir: /app
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: ./frontend
    container_name: tiersense_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    working_dir: /app
    command: >
      sh -c "npm install --legacy-peer-deps && npm run dev"
 
volumes:
  sharedlogs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.14.220.88,nfsvers=4,rw"
      device: ":/nfs/logs"
