import os
import re
import json
from collections import defaultdict

def parse_logs(log_path: str):
    """
    Parses the .ndjson log file generated by Filebeat from the host's auditd logs.
    """
    access_counts = defaultdict(int)

    if not os.path.exists(log_path):
        print(f"[WARN] Log file not found at: {log_path}. This is normal if no file activity has occurred yet.")
        return access_counts, {}

    print(f"[INFO] Parsing processed audit logs from: {log_path}")
    
    with open(log_path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            try:
                # Each line from Filebeat is a JSON object containing the original log message.
                log_entry = json.loads(line)
                message = log_entry.get("message", "")

                # We only care about logs that contain our specific monitoring key.
                if 'key="tiersense_monitoring"' not in message:
                    continue

                # Extract the full, absolute path of the file that was accessed.
                # The 'name=' field in auditd logs contains the path.
                path_match = re.search(r'name="([^"]+)"', message)
                
                if path_match:
                    # Normalize the path to handle any ".." or "." parts.
                    full_path = os.path.normpath(path_match.group(1))
                    
                    # We only want to count access to files, not directories themselves.
                    # A simple check is to see if it has a file extension or doesn't end with a slash.
                    if '.' in os.path.basename(full_path) or not full_path.endswith('/'):
                         access_counts[full_path] += 1

            except (json.JSONDecodeError, AttributeError):
                # Ignore lines that are not valid JSON or don't have a message field.
                continue
    
    print(f"[INFO] Parsing complete. Found {len(access_counts)} files with access events.")
    return access_counts, {}